global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "vllm-baseline"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "vllm-speculative"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8001"]

  - job_name: "dcgm-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["dcgm-exporter:9400"]